# Generated by Django 5.2.15 on 2026-06-25 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('profile_completed', 'Profile completed'), ('daily_challenge', 'Daily challenge completed'), ('workout_completed', 'Workout completed'), ('progress_post', 'Progress post created'), ('review_created', 'Review created'), ('purchase_made', 'Purchase made'), ('subscription_started', 'Subscription started'), ('streak_bonus', 'Streak bonus')], max_length=40)),
                ('points', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=180)),
                ('idempotency_key', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('user', 'idempotency_key'), name='unique_reward_event_per_user_key')],
            },
        ),
    ]
